### ISSUE TITLE
403: Forbidden

### ISSUE THREAD

**Issue by vbhavsar** [mariushe/cjenkins#3]
I am getting a "HTTPError: HTTP Error 403: Forbidden" error when I run cjenkins with valid -u and -p parameters. Going through the code, I didn't see the args being passed anywhere.

Stacktrace:
```
Traceback (most recent call last):
  File "cjenkins.py", line 83, in displayGui
    drawScreen(count, -1)
  File "cjenkins.py", line 138, in drawScreen
    row = readData(count, link, row, focusRow)
  File "cjenkins.py", line 144, in readData
    data = eval(urllib2.urlopen(link + "/api/python?depth=1&pretty=true").read());
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

**Comment by mariushe** [comment]
Hi.

Initially the script didn't support username and password, so it wasn't added to the monitor part of the system.

Now I've updated the code to use the username and password there as well.

Thanks for letting me know about this issue. Let me know if this fix worked for you. Thanks!

**Comment by vbhavsar** [comment]
Works now. Thanks for the quick fix! This tool is awesome.

**Comment by mariushe** [comment]
Great! Thanks :smile:
